#1.Create a 3*3 numpy array with random integers between 1 to 100 .Then interchange its rows and columns.

The code to create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns (transpose it):

```
import numpy as np

# Create a 3x3 numpy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array_3x3)

# Print the original and transposed arrays
print("Original Array:")
print(array_3x3)

print("\nTransposed Array:")
print(transposed_array)
```


In [1]:
import numpy as np

# Create a 3x3 numpy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array_3x3)

# Print the original and transposed arrays
print("Original Array:")
print(array_3x3)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[60 36 64]
 [21 38 58]
 [75 33 37]]

Transposed Array:
[[60 21 75]
 [36 38 33]
 [64 58 37]]


#2.Generate a 1D NumPy array with 10 elements. Reshape it into 2 * 5 array, then into a 5 * 2 array.
```
import numpy as np

# 1. Create a 3x3 numpy array with random integers between 1 and 100 and interchange its rows and columns
array_3x3 = np.random.randint(1, 101, size=(3, 3))
transposed_array = np.transpose(array_3x3)

print("Original 3x3 Array:")
print(array_3x3)
print("\nTransposed Array:")
print(transposed_array)

# 2. Generate a 1D NumPy array with 10 elements and reshape it into 2x5 and then into 5x2 arrays
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("\n1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)
```

In [2]:
import numpy as np

# 1. Create a 3x3 numpy array with random integers between 1 and 100 and interchange its rows and columns
array_3x3 = np.random.randint(1, 101, size=(3, 3))
transposed_array = np.transpose(array_3x3)

print("Original 3x3 Array:")
print(array_3x3)
print("\nTransposed Array:")
print(transposed_array)

# 2. Generate a 1D NumPy array with 10 elements and reshape it into 2x5 and then into 5x2 arrays
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("\n1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)


Original 3x3 Array:
[[75 52 48]
 [91 32 92]
 [60 10 85]]

Transposed Array:
[[75 91 60]
 [52 32 10]
 [48 92 85]]

1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#3.Create a 4 * 4 NumPy array with random float values.Add a border of zeroes around it, resulting in a 6 * 6 array.
```
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.random((4, 4))

# Add a border of zeroes around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the original and the bordered arrays
print("Original 4x4 Array:")
print(array_4x4)

print("\n6x6 Array with Zero Border:")
print(array_with_border)
```



In [3]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.random((4, 4))

# Add a border of zeroes around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the original and the bordered arrays
print("Original 4x4 Array:")
print(array_4x4)

print("\n6x6 Array with Zero Border:")
print(array_with_border)


Original 4x4 Array:
[[0.68665637 0.95506037 0.62561044 0.8998488 ]
 [0.09907326 0.32801958 0.76624843 0.23412265]
 [0.78476187 0.15442464 0.45441565 0.23129052]
 [0.25565198 0.98451995 0.45888292 0.86263365]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.68665637 0.95506037 0.62561044 0.8998488  0.        ]
 [0.         0.09907326 0.32801958 0.76624843 0.23412265 0.        ]
 [0.         0.78476187 0.15442464 0.45441565 0.23129052 0.        ]
 [0.         0.25565198 0.98451995 0.45888292 0.86263365 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#4.Using Numpy create an array of integers from  10 to 60 with  astep of 5.
```
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

# Print the array
print(array_integers)
```

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

# Print the array
print(array_integers)


[10 15 20 25 30 35 40 45 50 55 60]


#5.Create a NumPy array of strings['python','numpy','pandas'].Apply different case transformations (upercase,lowercase,title case,etc.) to each element.
```
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations to each element
upper_case = np.char.upper(string_array)       # Convert to uppercase
lower_case = np.char.lower(string_array)       # Convert to lowercase
title_case = np.char.title(string_array)       # Convert to title case
capitalize_case = np.char.capitalize(string_array)  # Capitalize first letter

# Print the results
print("Original Array:")
print(string_array)

print("\nUppercase:")
print(upper_case)

print("\nLowercase:")
print(lower_case)

print("\nTitle Case:")
print(title_case)

print("\nCapitalize:")
print(capitalize_case)
```

In [5]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations to each element
upper_case = np.char.upper(string_array)       # Convert to uppercase
lower_case = np.char.lower(string_array)       # Convert to lowercase
title_case = np.char.title(string_array)       # Convert to title case
capitalize_case = np.char.capitalize(string_array)  # Capitalize first letter

# Print the results
print("Original Array:")
print(string_array)

print("\nUppercase:")
print(upper_case)

print("\nLowercase:")
print(lower_case)

print("\nTitle Case:")
print(title_case)

print("\nCapitalize:")
print(capitalize_case)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


#6.Generate NumPy array of words.Insert a space between each character of every word in the array.
```
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Print the result
print("Original Array:")
print(words_array)

print("\nWords with Spaces:")
print(spaced_words)
```

In [6]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Print the result
print("Original Array:")
print(words_array)

print("\nWords with Spaces:")
print(spaced_words)


Original Array:
['python' 'numpy' 'pandas']

Words with Spaces:
['p y t h o n' 'n u m p y' 'p a n d a s']


#7.create two 2D NumPy arrays and perform element-wise addition,subtraction,multiplication and division.

```
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

# Perform element-wise operations
addition = array1 + array2              # Element-wise addition
subtraction = array1 - array2           # Element-wise subtraction
multiplication = array1 * array2        # Element-wise multiplication
division = array1 / array2              # Element-wise division

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)
```

In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

# Perform element-wise operations
addition = array1 + array2              # Element-wise addition
subtraction = array1 - array2           # Element-wise subtraction
multiplication = array1 * array2        # Element-wise multiplication
division = array1 / array2              # Element-wise division

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


#8.use NumPy to create a 5 * 5 identity matrix,then extract its diagonal elements.
```
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the results
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)
```

In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the results
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


#9.Generate a NumPy array of 100  random integers between 0 and 1000.Find and display all prime numbers in this array.
```
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Print the results
print("Random Array:")
print(random_array)

print("\nPrime Numbers:")
print(prime_numbers)
```

In [9]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Print the results
print("Random Array:")
print(random_array)

print("\nPrime Numbers:")
print(prime_numbers)


Random Array:
[829 442 702 865  71 242 393 418 329 850  34 215 569 439 888 894 487 593
 116 387 551 737 441 291 841 856 427 635 996 479 898 733 566 652 110 231
 818 272 791 377 711  17 993 186 259 884 291 606 408 143 214  87  96 954
 362 349 318 124 608 125 545 172 528 186 952 627 342 730 299 745 989 470
 547 330 757 365 616 551  57 583 353 611 670 921  11 760 365 787 407 196
 119 302 837 576 546 808 934 822 212 206]

Prime Numbers:
[829, 71, 569, 439, 487, 593, 479, 733, 17, 349, 547, 757, 353, 11, 787]


#10.Create a NumPy array representing daily temperatures for a month.Calculate and display the weekly averages.

```
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For demonstration, let's generate random temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.uniform(15, 35, size=30)

# Calculate the number of complete weeks and the remaining days
num_weeks = len(daily_temperatures) // 7
remaining_days = len(daily_temperatures) % 7

# Reshape the array into a 2D array for complete weeks
weekly_temperatures = daily_temperatures[:num_weeks * 7].reshape(num_weeks, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# If there are remaining days, calculate their average
if remaining_days > 0:
    last_week_average = np.mean(daily_temperatures[-remaining_days:])
    weekly_averages = np.append(weekly_averages, last_week_average)

# Print the results
print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)

```

In [11]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For demonstration, let's generate random temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.uniform(15, 35, size=30)

# Calculate the number of complete weeks and the remaining days
num_weeks = len(daily_temperatures) // 7
remaining_days = len(daily_temperatures) % 7

# Reshape the array into a 2D array for complete weeks
weekly_temperatures = daily_temperatures[:num_weeks * 7].reshape(num_weeks, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# If there are remaining days, calculate their average
if remaining_days > 0:
    last_week_average = np.mean(daily_temperatures[-remaining_days:])
    weekly_averages = np.append(weekly_averages, last_week_average)

# Print the results
print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[16.45315235 31.9800894  28.72247992 21.4422144  22.15980781 25.85796801
 30.81388966 25.88572583 24.39866595 29.88867079 17.46019065 30.98003436
 23.38663578 34.23518031 20.2374231  34.55422831 17.30259088 31.99147468
 21.14732326 28.40531716 18.67728203 21.12490178 15.16972075 15.50420412
 34.70691283 24.92851718 24.4366963  27.284159   26.74524744 27.13903079]

Weekly Averages:
[25.34708594 26.60501481 24.61651992 23.30787314 26.94213912]
